services:
  fitbet-backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: fitbet-backend
    ports:
      - "4000:4000"      
      - "5555:5555"      
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@fitbet-db:5432/fitbetDB?schema=public
      - NODE_ENV=development
    depends_on:
      - db
    restart: always
    networks:
      - fitbet-network
    volumes:
      - ./backend:/app
      - /app/node_modules
  
  db:
    container_name: fitbet-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fitbetDB
    ports:
      - "5432:5432"
    volumes:
      - fitbet-data:/var/lib/postgresql/data
    networks:
      - fitbet-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  fitbet-network:
    driver: bridge

volumes:
  fitbet-data: