services:

  fitbet-backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: fitbet-backend
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fitbetDB?schema=public
  
  db:
    container_name: fitbet-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fitbetDB
    ports:
    - 5432:5432
    volumes:
      - fitbet-data:/var/lib/postgresql/data

volumes:
  fitbet-data: {}