services:
  db:
    container_name: fitbet-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fitbetDB
    ports:
    - 5432:5432
    volumes:
      - fitbet-data:/var/lib/postgresql/data

volumes:
  fitbet-data: {}